--- 
linters: 
  disable: 
    - cyclop
    - depguard
    - dogsled
    - dupl
    - errname
    - errorlint
    - exhaustivestruct
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - goerr113
    - goheader
    - golint
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - ifshort
    - interfacer
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - scopelint
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
  enable: 
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - contextcheck
    - durationcheck
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goconst
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam
    - wastedassign
linters-settings: 
  gocritic: 
    enabled-tags: 
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
output: 
  format: line-number
  print-issued-lines: false
  print-linter-name: true
  sort-results: false
run: 
  allow-parallel-runners: false
  concurrency: 4
  issues-exit-code: 1
  skip-dirs-use-default: true
  tests: true
  timeout: 10m
