name: "Govuln"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '42 12 * * 2'

jobs:
  analyze:
    name: Vuln check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.14', '1.18', '1.20' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Scan for Vulnerabilities in Code
        uses: Templum/govulncheck-action@<version>
        with:
          go-version: ${{ matrix.go-version }}
          vulncheck-version: latest
          package: ./...
          fail-on-vuln: true
