name: License scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go        
        
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run FOSSA scan and upload build data
      uses: fossa-contrib/fossa-action@v1
      with:
        fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
        skip-test: true
